<?php

namespace App\Http\Controllers\Payroll;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use Fpdf\Fpdf;
use App\Models\UserDetail;

class PayrollPAYROLLPDFController extends Controller
{
    public function payrollPdf(Request $request){
        $PayrollDetails = json_decode($request->pr_col1);
        $pdf = new FPDF();

        //Add a new page
        $pdf->AddPage();

        // Set the font for the text
        $pdf->SetFont('Arial', 'B', 12);

        // Prints a cell with given text
        $pdf->Cell(190,7,'Beulah Land Christian College Inc.',0,1,'C');
        $pdf->SetFont('Arial', '', 12);
        $pdf->Cell(190,7,'Employee Payroll Sheet',0,1,'C');
        $pdf->Cell(190,7,'Cutoff Date:',0,1,'C');
        $pdf->Cell(190,7,$request->pr_col2,0,1,'C');

        // Employee Payroll Summary
        $total_net = 0;
        foreach ($PayrollDetails as $key => $employee) {
            $total_net += $employee->net_pay;
        }

        $total_tax = 0;
        foreach ($PayrollDetails as $key => $employee) {
            $total_tax += $employee->tax_deduction;
        }

        $total_ca = 0;
        foreach ($PayrollDetails as $key => $employee) {
            $total_ca += $employee->total_cash_advance;
        }

        $pdf->Ln(5);
        $pdf->SetFont('Arial', 'B', 12);
        $pdf->Cell(190,10,'Employee Payroll Summary',"T,B",1,'');
        $pdf->Cell(130,10,'Total Employee Payment: ',0,0,'');
        $pdf->Cell(60,10,number_format($total_net, 2, '.', ',') . " Php",0,1,'C');
        $pdf->Cell(130,10,'Total Employee Taxes: ',0,0,'');
        $pdf->Cell(60,10,number_format($total_tax, 2, '.', ',') . " Php",0,1,'C');
        $pdf->Cell(130,10,'Total Employee Cash Advance: ',0,0,'');
        $pdf->Cell(60,10,number_format($total_ca, 2, '.', ',') . " Php",0,1,'C');

        //Employee Payroll Information
        $pdf->Ln(5);
        $pdf->SetFont('Arial', 'B', 12);
        $pdf->Cell(190,10,'Employee Payroll Information',"T,B",1,'');

        //start of table
        //Table Header
        $pdf->Ln(3);
        $pdf->SetFont('Arial', 'B', 8);
        $pdf->Cell(10.1,7,'ID',1,0,'C');
        $pdf->Cell(36.1,7,'Employee Name',1,0,'C');
        $pdf->Cell(17.1,7,'Hours',1,0,'C');
        $pdf->Cell(21.1,7,'Rate',1,0,'C');
        $pdf->Cell(21.1,7,'Gross Pay',1,0,'C');
        $pdf->Cell(21.1,7,'Taxes',1,0,'C');
        $pdf->Cell(21.1,7,'Deductions',1,0,'C');
        $pdf->Cell(21.1,7,'Cash Advance',1,0,'C');
        $pdf->Cell(21.1,7,'Net Pay',1,1,'C');

        foreach ($PayrollDetails as $key => $employee) {
            $pdf->SetFont('Arial', '', 8);
            $pdf->Cell(10.1,7,$employee->employee_id,1,0,'C');
            $pdf->SetFont('Arial', '', 6);
            $pdf->Cell(36.1,7,$employee->full_name,1,0,'C');
            $pdf->SetFont('Arial', '', 8);
            $pdf->Cell(17.1,7,$employee->complete_hours,1,0,'C');
            $pdf->Cell(21.1,7,number_format($employee->rate, 2, '.', ',') . " Php",1,0,'C');
            $pdf->Cell(21.1,7,number_format($employee->gross_pay, 2, '.', ',') . " Php",1,0,'C');
            $pdf->Cell(21.1,7,number_format($employee->tax_deduction, 2, '.', ',') . " Php",1,0,'C');
            $pdf->Cell(21.1,7,number_format($employee->total_deduction, 2, '.', ',') . " Php",1,0,'C');
            $pdf->Cell(21.1,7,number_format($employee->total_cash_advance, 2, '.', ',') . " Php", 1,0,'C');
            $pdf->Cell(21.1,7,number_format($employee->net_pay, 2, '.', ',') . " Php",1,1,'C');
        }

        $pdf->Ln(40);
        $pdf->SetFont('Arial', 'B', 12);
        $pdf->Cell(8,10,'',0,0,'C');
        $pres_sign = "signature/president.png";
        $pdf->Image($pres_sign, $pdf->GetX() + 17, $pdf->GetY() - 7, 33.78);
        $pdf->Cell(70,10,'John Doe',0,0,'C');
        $pdf->Cell(30,10,'',0,0,'C');
        $pr_sign = "signature/".$employee->prm_id.".png";
        $pdf->Image($pr_sign, $pdf->GetX() + 17, $pdf->GetY() - 7, 33.78);
        $prm_name = UserDetail::where('login_id', $employee->prm_id)->first();
        $pdf->Cell(70,10,"$prm_name->fname $prm_name->mname $prm_name->lname",0,1,'C');

        $pdf->SetFont('Arial', 'B', 12);
        $pdf->Cell(8,10,'',0,0,'C');
        $pdf->Cell(70,10,'President','T',0,'C');
        $pdf->Cell(30,10,'',0,0,'C');
        $pdf->Cell(70,10,'Payroll Manager','T',1,'C');

        $pdf->Ln(30);
        $pdf->Cell(190,10,'Generated by OASYS','T,B',0,'C');

        $pdf->Output('F',"payrolls/payroll(" . $request->pr_col2 .").pdf");
        $pdf->Output();
        exit;
    }
}
